name: Dockerfiles
# Test and push dockerfiles when they change.
# Test for pull request, push dockerfiles when merged into main.
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - '**.Dockerfile'
      - .github/workflows/docker.yml
  pull_request:
  workflow_dispatch:

# Cancel in-progress runs of the same workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - label: ros2
            tag: rolling
            target: base
            platforms: "linux/amd64"
          - label: ros2
            tag: rolling
            target: dev
            platforms: "linux/amd64"
          - label: ros2
            tag: rolling
            target: full
            platforms: "linux/amd64"
          - label: ros2
            tag: jazzy
            target: base
            platforms: "linux/amd64,linux/arm64"
          - label: ros2
            tag: jazzy
            target: dev
            platforms: "linux/amd64,linux/arm64"
          - label: ros2
            tag: jazzy
            target: full
            platforms: "linux/amd64,linux/arm64"
          - label: ros2
            tag: humble
            target: base
            platforms: "linux/amd64,linux/arm64"
          - label: ros2
            tag: humble
            target: dev
            platforms: "linux/amd64,linux/arm64"
          - label: ros2
            tag: humble
            target: full
            platforms: "linux/amd64,linux/arm64"

    steps:
      - uses: actions/checkout@v4
      - name: Filter build
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docker:
              - src/${{ matrix.tag }}.Dockerfile
      - name: Set current date
        id: date
        run: |
          echo "date=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"
      - name: Use current date
        run: |
          echo "Current date is ${{ steps.date.outputs.date }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        if: ${{ steps.filter.outputs.docker == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          file: src/${{ matrix.tag }}.Dockerfile
          target: ${{ matrix.target }}
          platforms: ${{ matrix.platforms }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.label }}:${{ matrix.tag }}-${{ matrix.target }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.label }}:${{ matrix.tag }}-${{ matrix.target }}-${{ steps.date.outputs.date }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.label }}:${{ matrix.tag }}-${{ matrix.target }}
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ matrix.label }}:${{ matrix.tag }}-buildcache
          cache-to: |
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ matrix.label }}:${{ matrix.tag }}-buildcache,mode=max

  complete:
    needs:
      - docker
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: echo "Completed successfully!"
